version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports: 
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./client:/usr/src/531logger/client
      - node_modules_frontend:/usr/src/531logger/client/node_modules
    command: npm run start
    networks: 
      - app-network
    restart: unless-stopped
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    ports: 
      - "5000:5000"
    volumes:
        - .:/usr/src/531logger/api
        - node_modules_backend:/usr/src/531logger/api/node_modules
    command: npm run server
    env_file: .env
    environment:
      - PORT=$PORT
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  node_modules_backend:
  node_modules_frontend:
