version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    container_name: client
    ports: 
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./client:/usr/src/531logger/client
      - node_modules_frontend:/usr/src/531logger/client/node_modules
    command: ./wait-for.sh mongodb:27017 -- npm run start
    networks: 
      - app-network
    restart: unless-stopped
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: backend-api
    ports: 
      - "5000:5000"
    volumes:
        - ./backend:/usr/src/531logger/api
        - node_modules_backend:/usr/src/531logger/api/node_modules
    command: ./wait-for.sh mongodb:27017 -- npm run server
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    networks:
      - app-network
    restart: unless-stopped
  db:
    image: mongo:4.1.8-xenial
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - '27017:27017'
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    expose:
      - '80'
    ports:
      - '80:80'
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - backend-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules_backend:
  node_modules_frontend:
  web-root:
